### ISSUE TITLE
Exist a option for send a message for all friends list?

### ISSUE THREAD

**Issue by Cyb3rG0D7** [socialbotspy/FacebookPy#22]
Existe una opción para enviar un mensaje específico a todos mis amigos de facebook? o una opción para poster lo mismo en varios grupos o fanpages?

**Comment by ishandutta2007** [comment]
Please translate into english. For message you can automate with facebooks internal chatbot, you don't need external bot.

**Comment by Cyb3rG0D7** [comment]
Is it in messenger?
Where do I find that option?
but the same could be added to the bot to do everything in the bot

**Comment by ishandutta2007** [comment]
You are asking it on wrong website, anyways I will provide you the link.
https://www.facebook.com/help/1698046970464236
